### ISSUE TITLE
PlayTest Mode can be enabled at the same time than multiplayer features by using a feature from the game browser

### ISSUE THREAD

**Issue by Mimigris** [monokotech/EasyRPG-Multiplayer-Native#5]
#### Player platform:
Windows, latest multiplayer release.

#### Describe the issue in detail and how to reproduce it:
One feature of the main EasyRPG Player not properly documented is that, in the game browser of the Player, it is possible to start the selected entry in playtest mode by pressing Shift or F9 instead of enter. (More info if needed in [issue #3139 of the main project](https://github.com/EasyRPG/Player/issues/3139), and here is a screen of the scene where you need to press Shift or F9 to start a game in playtest mode):
![image](https://github.com/monokotech/EasyRPG-Multiplayer-Native/assets/108797333/3edf3183-c747-49c9-b184-f1d2024aded8)

With this feature known, if you launch a game from the game browser without using this, then exit the game, and then relaunch it by pressing Shift or F9, you will be able to use both playtest features and multiplayer features.
![image](https://github.com/monokotech/EasyRPG-Multiplayer-Native/assets/108797333/ceaa13f5-2357-461b-8074-38512e866d5e)

Having both features enabled at the same time doesn't seem to be intended from what I can read on [your pull request in the main repo of the Player](https://github.com/EasyRPG/Player/pull/3138#issuecomment-1785092414), so I thought that it could be useful to report it here.

As an addition on the feedback side, locking the playtest mode to not be available in multiplayer may seem logic while playing with people that you may not know to have everyone play with the same rules and to not break the immersion, but in some cases, it may be useful to be able to have access to the debug menu while playing a game with other players, for example while testing a game in development in a team or a game that has bugs preventing you from playing it properly, and where you may need to walk through walls or teleport to be able to advance further in the game. I'm not sure if it could be possible, but maybe having the possibility to create rooms where only players using the normal mode or allowing any kind of player could be possible, that's just an idea.

**Comment by monokotech** [comment]
I can understand your needs, not just what you said. Sometimes, I need to go somewhere while playing with a friend, it becomes almost impossible if I can't read a certain variable.

If we want to use debug menu in the multiplayer mode, I think we can unlock the cheating by entering `!cheat`. This reminds players to confirm if they're cheating or helps them to avoid forgetting to turn off PlayTest in multiplayer mode.

#### To resolve the problem of the button conflict, I have several ways:

##### In normal mode

Use chat command to enable PlayTest mode. then use `!debug` to show debug menu.

!cheat => !test_play => !debug

##### In PlayTest mode

Open debug menu, select **Multiplayer Chat**, and use `!notifications`  instead of F9.

##### Other

Use new buttons for multiplayer. This may require replacing a lot of things and getting used to the new buttons again.

---

"With this feature known, if you launch a game from the game browser without using this, then exit the game, and then relaunch it by pressing Shift or F9, you will be able to use both playtest features and multiplayer features."

This bug will be fixed when the above problems are resolved.

---

Thank you for your report!

**Comment by Mimigris** [comment]
> I can understand your needs, not just what you said. Sometimes, I need to go somewhere while playing with a friend, it becomes almost impossible if I can't read a certain variable.
If we want to use debug menu in the multiplayer mode, I think we can unlock the cheating by entering !cheat. This reminds players to confirm if they're cheating or helps them to avoid forgetting to turn off PlayTest in multiplayer mode.

I noticed that you added the !cheat command while looking at the history of the dev branch but wasn't aware of its function, that's exactly what is needed when wanting to play with other players so I'm glad that you made that, it's perfect as-is. 👍 

As for the fact that the keys are causing conflicts, this is something that was already reported to you and that is known, so I didn't wanted to report it here. What I think would be the best approach here would be to remap the keys used for the multiplayer features in the default configuration to new keys, and add the possibility to remap these keys in the settings menu of the Player to still allow you to map your multiplayer keys to the specific slots that you wanted if needed, so everyone could have what they want with an approach like that, though in the end, that's just my opinion.

**Comment by monokotech** [comment]
I have made some fixes, the PlayTest Mode can now be enabled in multiplayer.

You can enter `!cheat` followed by `!debug` to show the debug menu, and the PlayTest mode is also enabled. If you want to restore to normal mode, just enter `!cheat` again, all debug things are gone.

> What I think would be the best approach here would be to remap the keys used for the multiplayer features in the default configuration to new keys

I hope to make full use of the idle keys e.g. F9 and F10 for multiplayer features in normal mode. If you rely heavily on the multiplayer under the debug mode, you can remap these keys. Multiplayer keys remapping are now supported.

**Comment by Mimigris** [comment]
> I have made some fixes, the PlayTest Mode can now be enabled in multiplayer.

That seems to work great from what I can see, having the possibility to enable and disable the playtest mode on the fly can be really be useful. ❤️ 

> I hope to make full use of the idle keys e.g. F9 and F10 for multiplayer features in normal mode. If you rely heavily on the multiplayer under the debug mode, you can remap these keys. Multiplayer keys remapping are now supported.

That seems to work for the notification and chat keys (I've remapped mine to F6 and F8 to not have any conflict), but from what I can see, the mute key is not present in the settings and cannot be remapped, is it intended?

**Comment by monokotech** [comment]
> but from what I can see, the mute key is not present in the settings and cannot be remapped, is it intended?

I just forgot to add mute key remapping to settings. Now you can remap the mute key.
